// app/(checkout)/layout.tsx
import { Container, Header } from '@/shared/components/shared';
import { Metadata } from 'next';
import { Suspense } from 'react';
import { cookies } from 'next/headers';

export const metadata: Metadata = {
    title: 'M W S | Корзина',
    description: 'Generated by create next app',
};

export default async function CheckoutLayout({ children }: { children: React.ReactNode }) {
    // Получаем город из cookies на сервере
    const cookieStore = await cookies();
    const currentCity = cookieStore.get('selectedCity')?.value || '';

    // Данные городов
    const citiesData = [
        {
            id: "5a5963df-4e9a-45d2-aa7b-2e2a1a5e704d",
            name: "Гикалова",
            code: "3"
        },
        {
            id: "8740e9b6-ff6e-481e-b694-dc020cdf7bc4",
            name: "Парковая",
            code: "2"
        },
        {
            id: "8e57e25d-8c9c-486d-b41d-ac96a2c1f4cc",
            name: "Сибирский тракт",
            code: "1"
        }
    ];

    return (
        <main className="min-h-screen bg-black">
            <Container>
                <Suspense>
                    <Header
                        hasSearch={false}
                        hasCart={false}
                        className="border-b-gray-200"
                        cities={citiesData}
                        currentCity={currentCity}
                        // Не показываем модальное окно в checkout
                        showCityModal={false}
                    />
                </Suspense>
                {children}
            </Container>
        </main>
    );
}
